name: faith_fund
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  get: ^4.6.6
  gap: ^3.0.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  image_picker: ^1.1.2
  image_cropper: ^7.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  form_field_validator: ^1.1.0
  keyboard_dismisser: ^3.0.0
  rmdev_widgets:
    path: /Users/Rychid/Documents/projects/personal/mobile/packages/rmdev_widgets
  cloud_firestore: ^5.2.0
  get_secure_storage: ^1.0.5
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/

#   example:
  fonts:
    - family: Champ
      fonts:
        - asset: assets/images/Champ-Black.ttf
          weight: 900

